apiVersion: auth.versa-stack.io/v1alpha1
kind: ResourceDefinition
metadata:
  name: hydras
  namespace: versa-stack-system
spec:
  schema:
    group: auth.versa-stack.io
    version: v1alpha1
    kind: Hydra
    plural: hydras
    scope: Namespaced
    shortNames:
      - hy
    categories:
      - versa
      - versa-auth
    printerColumns:
      - name: Issuer
        type: string
        jsonPath: .spec.urls.issuer
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - urls
          properties:
            chart:
              type: object
              properties:
                version:
                  type: string
                  default: "0.40.1"
                valuesOverride:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            urls:
              type: object
              required:
                - issuer
                - consent
                - login
                - logout
              properties:
                issuer:
                  type: string
                consent:
                  type: string
                login:
                  type: string
                logout:
                  type: string
            oidc:
              type: object
              properties:
                subjectIdentifiers:
                  type: object
                  properties:
                    supportedTypes:
                      type: array
                      items:
                        type: string
                    pairwiseSalt:
                      type: string
            cors:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                allowedOrigins:
                  type: array
                  items:
                    type: string
                allowedMethods:
                  type: array
                  items:
                    type: string
                allowedHeaders:
                  type: array
                  items:
                    type: string
            ingress:
              type: object
              properties:
                public:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                admin:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            database:
              type: object
              properties:
                engine:
                  type: string
                  default: postgresql
                version:
                  type: string
                topology:
                  type: string
                replicas:
                  type: integer
                  default: 1
                storage:
                  type: string
                  default: "10Gi"
                storageClassName:
                  type: string
                resources:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: string

  kclSource:
    oci:
      repository: ghcr.io/versa-stack/auth.versa-stack.io
      tag: latest
      path: hydra/main.k
