apiVersion: auth.versa-stack.io/v1alpha1
kind: ResourceDefinition
metadata:
  name: kratoses
  namespace: versa-stack-system
spec:
  schema:
    group: auth.versa-stack.io
    version: v1alpha1
    kind: Kratos
    plural: kratoses
    scope: Namespaced
    shortNames:
      - kr
    categories:
      - versa
      - versa-auth
    printerColumns:
      - name: PublicURL
        type: string
        jsonPath: .spec.serve.publicBaseUrl
    openAPIV3Schema:
      type: object
      required:
        - spec
      properties:
        spec:
          type: object
          required:
            - serve
            - secrets
          properties:
            chart:
              type: object
              properties:
                version:
                  type: string
                  default: "0.50.1"
                valuesOverride:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            serve:
              type: object
              required:
                - publicBaseUrl
              properties:
                publicBaseUrl:
                  type: string
                adminBaseUrl:
                  type: string
            selfservice:
              type: object
              properties:
                defaultBrowserReturnUrl:
                  type: string
                flows:
                  type: object
                  properties:
                    loginUiUrl:
                      type: string
                    registrationUiUrl:
                      type: string
                    registrationEnabled:
                      type: boolean
                      default: true
                    verificationUiUrl:
                      type: string
                    verificationEnabled:
                      type: boolean
                      default: true
                    recoveryUiUrl:
                      type: string
                    recoveryEnabled:
                      type: boolean
                      default: true
                    settingsUiUrl:
                      type: string
                methods:
                  type: object
                  properties:
                    password:
                      type: boolean
                      default: true
            identity:
              type: object
              properties:
                defaultSchemaId:
                  type: string
                  default: default
                schemas:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - url
                    properties:
                      id:
                        type: string
                      url:
                        type: string
            secrets:
              type: object
              required:
                - cookie
              properties:
                cookie:
                  type: string
                cipher:
                  type: string
            cors:
              type: object
              properties:
                enabled:
                  type: boolean
                  default: true
                allowedOrigins:
                  type: array
                  items:
                    type: string
            ingress:
              type: object
              properties:
                public:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                admin:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            database:
              type: object
              properties:
                engine:
                  type: string
                  default: postgresql
                version:
                  type: string
                topology:
                  type: string
                replicas:
                  type: integer
                  default: 1
                storage:
                  type: string
                  default: "10Gi"
                storageClassName:
                  type: string
                resources:
                  type: object
                  additionalProperties:
                    type: object
                    additionalProperties:
                      type: string

  kclSource:
    oci:
      repository: ghcr.io/versa-stack/auth.versa-stack.io
      tag: latest
      path: kratos/main.k
